baseURL = "https://keen-shoes.surge.sh/"
languageCode = "en-us"
title = "Stefan BC Law"
disableKinds = ["taxonomy", "taxonomyTerm"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Practice Areas"
    url = "/practice-areas/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[params]
  dateFormat = "Jan 2, 2006"
  description = "Criminal defense attorney practicing law in the Southern California area."

[blackfriday]
  hrefTargetBlank = true
  noreferrerLinks = true