baseURL = "https://stefanbclaw.com/"
languageCode = "en-us"
title = "Stefan BC at Law"
disableKinds = ["taxonomy", "taxonomyTerm"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Practice Areas"
    url = "/practice-areas/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[params]
  dateFormat = "Jan 2, 2006"
  description = "I am an attorney at law offering competent, affordable legal defense for clients of all economic, racial, and ethnic backgrounds across the Southern California area."
  images = ["/images/stefan.jpg"]

[blackfriday]
  hrefTargetBlank = true
  noreferrerLinks = true