---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/blog
  label: Blog
  create: all
  match: "**/*"
- type: document
  path: src/about/about.md
  label: About
- type: directory
  path: src/testimonials
  label: Testimonials
  create: all
  match: "**/*md"
  exclude: njk
- type: directory
  path: src/practice-areas
  label: Practice Areas
  create: all
  match: "**/*md"
  exclude: njk
upload_dir: src/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
